// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlP8--L8Jy86HmRRYoeNAt-L8qrBpX0I',
    appId: '1:504863493525:web:fadf4a6433006e20317a9c',
    messagingSenderId: '504863493525',
    projectId: 'nextsnap-b1058',
    authDomain: 'nextsnap-b1058.firebaseapp.com',
    storageBucket: 'nextsnap-b1058.firebasestorage.app',
    measurementId: 'G-L1S479RSHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdc-xbxkaBKzyMDb5yiCFJ9NJbGjw4Anw',
    appId: '1:504863493525:android:ed115aa979262c13317a9c',
    messagingSenderId: '504863493525',
    projectId: 'nextsnap-b1058',
    storageBucket: 'nextsnap-b1058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBih7bE1ZxNRRnTP3LL7huyWhvXrffJ-kE',
    appId: '1:504863493525:ios:0f2b3a4856bcb62b317a9c',
    messagingSenderId: '504863493525',
    projectId: 'nextsnap-b1058',
    storageBucket: 'nextsnap-b1058.firebasestorage.app',
    iosBundleId: 'com.example.photoGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBih7bE1ZxNRRnTP3LL7huyWhvXrffJ-kE',
    appId: '1:504863493525:ios:a89ff3d0920bd7ab317a9c',
    messagingSenderId: '504863493525',
    projectId: 'nextsnap-b1058',
    storageBucket: 'nextsnap-b1058.firebasestorage.app',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvlP8--L8Jy86HmRRYoeNAt-L8qrBpX0I',
    appId: '1:504863493525:web:c3ebda77726bf0b5317a9c',
    messagingSenderId: '504863493525',
    projectId: 'nextsnap-b1058',
    authDomain: 'nextsnap-b1058.firebaseapp.com',
    storageBucket: 'nextsnap-b1058.firebasestorage.app',
    measurementId: 'G-TTJ1ZDD73L',
  );
}
